theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
rulers = [80]
auto-completion = true
auto-save = true
auto-format = true
text-width = 80
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.whitespace.render]
space = "all"
tab = "all"

# [editor.soft-wrap]
# enable = true
# max-wrap = 25
# max-indent-retain = 0
# wrap-indicator = "┊"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.search]
smart-case = false

[editor.lsp]
enable = true
auto-signature-help = true
display-messages = true

[keys.normal]
S-f = ":format"
