[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "xml"
formatter = { command = "tidy", args = [
  "-q",
  "-xml",
  "--show-errors",
  "0",
  "--show-warnings",
  "0",
  "--force-output",
  "--indent",
  "auto",
  "--vertical-space",
  "yes",
  "--tidy-mark",
  "no",
  "-wrap",
  "120",
] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "markdown"] }

[[language]]
name = "rust"
auto-format = true

roots = ["Cargo.toml", "Cargo.lock"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
